# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]
env:                                              
  MINECRAFT_VERSION: 1.20.4                        
  VERSION: 1.0.3+1.20.4
  RELEASE_NAME: Mystery Stat Mod 1.0.3 for Minecraft 1.20.4
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}           


jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
          21,    # Current Java LTS
        ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: Publish (CurseForge/Modrinth/GitHub)
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          modrinth-featured: true
          
          github-token: "${{env.GITHUB_TOKEN}}"

          files: |
            build/libs/*-[0-9].[0-9].[0-9].jar

          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: release
          #changelog-file: CHANGELOG.md                                      #The file in which the changes of your new update are specified (the path starts at your project root)

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"