name: release

on:
    release:
        types: [published]

env:                                              
  MINECRAFT_VERSION: 1.20.4                        
  VERSION: 1.0.4+1.20.4
  RELEASE_NAME: Mystery Stat Mod 1.0.4 for Minecraft 1.20.4
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}           

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Build release
              run: ./gradlew build

            - name: Publish (Modrinth/GitHub)
              uses: Kir-Antipov/mc-publish@v3.3.0
              with:
                modrinth-token: "${{env.MODRINTH_TOKEN}}"
                modrinth-featured: true
                  
                github-token: "${{env.GITHUB_TOKEN}}"
        
                files: |
                  build/libs/*-[0-9].[0-9].[0-9].jar
        
                name: "${{env.RELEASE_NAME}}"                             
                version: "${{env.VERSION}}"
                version-type: release
                #changelog-file: CHANGELOG.md                                      #The file in which the changes of your new update are specified (the path starts at your project root)
        
                loaders: fabric
                game-versions: "${{env.MINECRAFT_VERSION}}"
                java: "${{env.JAVA_VERSION}}"